name: 'Run prettify'
on:
   pull_request:
   push:
      branches: [main]

permissions: {}

jobs:
   prettier:
      permissions:
        contents: read  # for actions/checkout to fetch code
      name: Prettier Check
      runs-on: ubuntu-latest
      steps:
         - name: Harden the runner (Audit all outbound calls)
           uses: step-security/harden-runner@v2
           with:
             egress-policy: audit

         - name: Checkout Repository
           uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

         - name: Enforce Prettier
           run: npx prettier --check .
